# Generated by Django 4.2.26 on 2026-02-27 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="jobapplication",
            name="job_description",
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name="jobapplication",
            name="jobtype",
            field=models.CharField(
                choices=[
                    ("Remote", "Remote"),
                    ("Hybrid", "Hybrid"),
                    ("On-site", "On-site"),
                ],
                default="On-site",
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="jobapplication",
            name="location",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="jobapplication",
            name="salary",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=12, null=True
            ),
        ),
    ]
