# Generated by Django 4.2.26 on 2026-03-04 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0002_jobapplication_job_description_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="jobapplication",
            name="ats_score",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
