# Generated by Django 4.2.29 on 2026-03-06 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0003_jobapplication_ats_score"),
    ]

    operations = [
        migrations.AlterField(
            model_name="jobapplication",
            name="applied_date",
            field=models.DateField(auto_now_add=True),
        ),
    ]
