# Generated by Django 4.2.29 on 2026-03-06 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0004_alter_jobapplication_applied_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="jobapplication",
            name="job_description",
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name="jobapplication",
            name="jobtype",
            field=models.CharField(default="On-site", max_length=10),
        ),
        migrations.AlterField(
            model_name="jobapplication",
            name="salary",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="jobapplication",
            name="status",
            field=models.CharField(default="Applied", max_length=50),
        ),
    ]
