# Generated by Django 4.2.29 on 2026-03-06 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0005_alter_jobapplication_job_description_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="jobapplication",
            name="job_description",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="jobapplication",
            name="jobtype",
            field=models.CharField(default="On-site", max_length=20),
        ),
    ]
